---
title: "EECE 535_HW1_Yuxuan Ren"
author: "Yuxuan Ren"
date: "2023-02-19"

---


```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)
library(ggplot2)
library(dplyr)
library(patchwork)
library(ggpubr)
library(cowplot)
```


```{r Dataset Overview}
# A quick preview of the dataset and its variables using head() 
rm(diamonds)
head(diamonds)
# 10 variables representing various attributes of diamonds are incorporated in the dataset.
# As a diamond seller, I concerned most about the prices.
# In the following plot, I will investigate the attributes that have greater impact on prices and try to find the diamonds with the highest profit.
```

```{r PLot 1 Distribution of Diamond Prices}
# It's important for a diamond seller to understand the distribution of diamond prices, to price diamonds effectively as well as to make highest profits.

# Create a histogram to display the distribution of diamond prices
diamonds %>%
  ggplot(aes(x = price)) +
  geom_histogram(bins = 60, fill = "grey", color = "black") +
  labs(title = "Distribution of Diamond Prices", x = "Price (USD)", y = "Count")

# Plot 1 shows the price distribution of diamonds. The x-axis represents the price range and the y-axis represents the count of diamonds within that price range. Most diamonds range from $0 to $10,000, with some extremes. The distribution is right-skewed, with a long tail of higher-priced diamonds. This indicates that there is a market for expensive, high-quality diamonds, while there are also many lower-priced diamonds available.
```

```{r Plot 2 Distribution of Diamond Prices Classified by Cut, Color, and Clarity }
# This attributes of diamonds is important for a diamond seller to consider when pricing their own diamonds. Here I investigate the impact of classifiable attributes on price, that is, cut, color, and clarity. By analyzing the price distributions by various attributes, a diamond seller can determine the optimal price range for their diamonds based on their cut quality. Additionally, they may be able to use this information to market diamonds with higher quality cuts at a premium price, potentially increasing their profits.

# Colored the plot by cut, color, and clarity
p1 <- diamonds %>%
  ggplot(aes(x = price, y = after_stat(count), color = cut)) +
  geom_freqpoly(binwidth = 500) +
  xlim(0, 6000) +
  labs(x = NULL, y = "Count", color = "Cut Quality") +
  guides(color = guide_legend(ncol = 2))

p2 <- diamonds %>%
  ggplot(aes(x = price, y = after_stat(count), color = color)) +
  geom_freqpoly(binwidth = 500) +
  xlim(0, 6000) +
  labs(x = NULL, y = "Count", color = "Color") +
  guides(color = guide_legend(ncol = 2))

p3 <- diamonds %>%
  ggplot(aes(x = price, y = after_stat(count), color = clarity)) +
  geom_freqpoly(binwidth = 500) +
  xlim(0, 6000) +
  labs(x = "Price (USD)", y = "Count", color = "Clarity Quality") +
  guides(color = guide_legend(ncol = 2))

# Combine the plots 
plot_grid(p1, p2, p3, ncol = 1, align = "v", axis = "lr")

# From this plot, we can see that there are differences in the price distributions for different cut, color, and clarity categories. In general, the number of diamonds decreases as the quality decreases. This suggests that buyers are willing to pay more for diamonds with higher quality cut, color, and clarity.
# Moreover, for a certain price range, say $800 to $1,200, the diamonds with an "Ideal" cut, "E" or "G" color, and "VS2" clarity are more available. A diamond seller may be able to command higher prices for diamonds with this qualities.
```

```{r Plot 3 Scatter Plot of of Diamond Prices and Carat}
# Then I am interested in the effect of carat. Are higher carat gemstones more expensive, is there a difference in various cut and clarity categories?

# Scatter plot of carat and prices, faceted by cut, colored by clarity
ggplot(diamonds, aes(x = price, y = carat, color = clarity)) +
  geom_point(alpha = 0.5, size = 1.5, shape = 16) +
  facet_wrap(~ cut) +
  labs(x = "Price", y = "Carat", color = "Clarity Quality") +
  scale_x_continuous(name = "Price") +
  scale_y_continuous(name = "Carat") +
  ggtitle("Scatter Plot of of Diamond Prices and Carat")

# There is a positive relationship between prices and carat across all levels of clarity and cut. As carat increases, prices also appear to increase. However, the relationship is not strictly linear. The curvature in the plot suggests that the effect of carat might be smaller at higher carat values. Moreover, the relationship is not identical across all categories. For example, within the "Ideal" cut category, the positive relationship is stronger within the "Ideal" cut category, followed by "Premium" cut category, and weaker for the "Very Good" and "Good" cut categories.
```

```{r Plot 4 Diamonds with Highest Profit}
# Here we calculate the profit, which is determined by profit - predicted price. Then focused on identifying the diamonds with the highest profits.

# Predict diamond price by linear regression
model <- lm(price ~ carat + cut + color + clarity + depth + table, data = diamonds)
diamonds$predicted_price <- predict(model)

# Calculate profit 
diamonds$profit <- diamonds$price - diamonds$predicted_price

# Sort diamonds by profit and select the top 500
top_diamonds <- diamonds %>% arrange(desc(profit)) %>% head(500)
# Color the plot by cut
ggplot(top_diamonds, aes(x = predicted_price, y = profit, color = cut)) +
  geom_point(alpha = 0.7) +
  labs(x = "Predicted Price (USD)", y = "Profit (USD)", color = "Cut Quality") +
  ggtitle("Diamonds with Highest Profit")

# Various types of cut are mixed in this plot, to make the plot more readable, facet the plot by cut.

# Facet the plot by cut
ggplot(top_diamonds, aes(x = predicted_price, y = profit, color = cut)) +
  facet_wrap(~cut) +
  geom_point(alpha = 0.7) +
  labs(x = "Predicted Price (USD)", y = "Profit (USD)", color = "Cut Quality") +
  ggtitle("Diamonds with Highest Profit")

# This plot shows the top 500 diamonds with the highest profit colored by cut quality. The diamonds with "very good" and "Premium" cut quality appear to have prices that are significantly higher than what would be expected based on their attributes. As a diamond seller, this plot helps me identify the diamonds with the highest profit margin. By identifying these diamonds, I can focus my sales efforts on the most profitable diamonds and potentially increase my profits.
```
